"use client";
import {useEffect,useMemo,useState} from "react";
import {clinicConfig} from "@/clinic.config";

const days=[{id:0,name:"الأحد"},{id:1,name:"الاثنين"},{id:2,name:"الثلاثاء"},{id:3,name:"الأربعاء"},{id:4,name:"الخميس"},{id:5,name:"الجمعة"},{id:6,name:"السبت"}];
const fmt=(date:string)=>new Date(date+"T12:00:00").toLocaleDateString("ar-PS",{weekday:"long",year:"numeric",month:"long",day:"numeric"});
const addMinutes=(time:string,n:number)=>{const [h,m]=time.split(":").map(Number);const total=h*60+m+n;return `${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`};

export default function Home(){
 const [screen,setScreen]=useState<"booking"|"login"|"doctor">("booking");
 return screen==="booking"?<Booking goLogin={()=>setScreen("login")}/>:screen==="login"?<Login back={()=>setScreen("booking")} success={()=>setScreen("doctor")}/>:<DoctorDashboard logout={async()=>{await fetch('/api/doctor-auth',{method:'DELETE'});setScreen('booking')}}/>;
}

function Booking({goLogin}:{goLogin:()=>void}){
 const [data,setData]=useState<any>({doctor:null,availability:[],occupied:[]});const [date,setDate]=useState("");const [time,setTime]=useState("");const [name,setName]=useState("");const [phone,setPhone]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [code,setCode]=useState("");
 const load=async()=>{try{const r=await fetch('/api/clinic?public=1',{cache:'no-store'});const j=await r.json();if(!r.ok){setError(j.error||'تعذر الاتصال بقاعدة البيانات');return}setData({doctor:j.doctor??null,availability:j.availability??[],occupied:j.occupied??[]})}catch{setError('تعذر الاتصال بقاعدة البيانات')}};useEffect(()=>{void load()},[]);
 const schedule=useMemo(()=>date?(data.availability??[]).find((a:any)=>a.weekday===new Date(date+'T12:00:00').getDay()):null,[date,data.availability]);
 const slots=useMemo(()=>{if(!schedule)return[];const taken=new Set((data.occupied??[]).filter((x:any)=>x.appointment_date===date).map((x:any)=>x.appointment_time));const result=[];let t=schedule.start_time;while(t<schedule.end_time){if(!taken.has(t))result.push(t);t=addMinutes(t,schedule.slot_minutes)}return result},[schedule,date,data.occupied]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");setBusy(true);const r=await fetch('/api/clinic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'book',name,phone,date,time})});const j=await r.json();setBusy(false);if(!r.ok)return setError(j.error);setCode(j.confirmation);await load()};
 const min=new Date().toISOString().slice(0,10);const maxD=new Date();maxD.setDate(maxD.getDate()+60);const max=maxD.toISOString().slice(0,10);
 if(code)return <main dir="rtl" className="public-page"><Top onDoctor={goLogin}/><section className="success-card panel"><div className="check">✓</div><h1>تم حجز موعدك</h1><p>احتفظ برقم الحجز، وستتواصل العيادة معك عند الحاجة.</p><strong className="code">{code}</strong><div className="summary"><p><b>الطبيب:</b> {data.doctor?.name}</p><p><b>التاريخ:</b> {fmt(date)}</p><p><b>الوقت:</b> {time}</p><p><b>رقم الهاتف:</b> {phone}</p></div><button className="primary" onClick={()=>{setCode('');setDate('');setTime('');setName('');setPhone('')}}>حجز موعد آخر</button></section></main>;
 return <main dir="rtl" className="public-page"><Top onDoctor={goLogin}/><section className="hero"><span>حجز إلكتروني سريع</span><h1>احجز موعدك بسهولة</h1><p>اختَر اليوم والوقت المناسب، ثم أدخل اسمك ورقم هاتفك فقط.</p></section><form className="booking panel" onSubmit={submit}><div className="doctor-box"><div className="doctor-avatar">د</div><div><small>الطبيب</small><h2>{data.doctor?.name||'جارٍ التحميل...'}</h2><p>{data.doctor?.specialty}</p></div></div><div className="step"><i>1</i><div><h3>اختَر التاريخ</h3><p>أيام الدوام المتاحة مميزة في النظام</p></div></div><input className="date-input" type="date" min={min} max={max} value={date} onChange={e=>{setDate(e.target.value);setTime('')}} required/>{date&&!schedule&&<p className="error">لا يوجد دوام في هذا اليوم، اختَر يومًا آخر.</p>}{schedule&&<><div className="step"><i>2</i><div><h3>اختَر الوقت</h3><p>تظهر الأوقات غير المحجوزة فقط</p></div></div><div className="slots">{slots.length?slots.map((s:string)=><button type="button" className={time===s?'selected':''} onClick={()=>setTime(s)} key={s}>{s}</button>):<p>لا توجد أوقات متاحة في هذا اليوم.</p>}</div></>}{time&&<><div className="step"><i>3</i><div><h3>بيانات التواصل</h3><p>الاسم ورقم الهاتف فقط</p></div></div><div className="contact"><label>الاسم الكامل<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>رقم الهاتف<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="0590000000" inputMode="tel" pattern="0[0-9]{8,9}" required/></label></div></>}{error&&<p className="error">{error}</p>}<button className="primary submit" disabled={!time||busy}>{busy?'جارٍ الحجز...':'تأكيد الحجز'}</button></form></main>
}

function Top({onDoctor}:{onDoctor:()=>void}){return <header className="top"><div className="logo"><b>♡</b>{clinicConfig.clinicName}</div><button className="ghost" onClick={onDoctor}>دخول الطبيب</button></header>}

function Login({back,success}:{back:()=>void;success:()=>void}){const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");const r=await fetch('/api/doctor-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok){const j=await r.json();return setError(j.error)}success()};return <main dir="rtl" className="login-page"><form className="login panel" onSubmit={submit}><div className="logo center"><b>♡</b>{clinicConfig.clinicName}</div><h1>دخول الطبيب</h1><p>هذه الصفحة مخصصة للطبيب فقط</p><label>البريد الإلكتروني<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>كلمة المرور<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="error">{error}</p>}<button className="primary">تسجيل الدخول</button><button type="button" className="link" onClick={back}>العودة لصفحة الحجز</button></form></main>}

function DoctorDashboard({logout}:{logout:()=>void}){const [data,setData]=useState<any>({doctor:null,appointments:[],availability:[]});const [tab,setTab]=useState<"appointments"|"availability">("appointments");const [selected,setSelected]=useState<number[]>([]);const [start,setStart]=useState("09:00");const [end,setEnd]=useState("14:00");const [duration,setDuration]=useState(30);const [message,setMessage]=useState("");
 const load=async()=>{const r=await fetch('/api/clinic',{cache:'no-store'});if(r.status===401)return logout();const j=await r.json();if(!r.ok){setMessage(j.error||'تعذر تحميل البيانات');return}const availability=j.availability??[];setData({...j,appointments:j.appointments??[],availability});setSelected(availability.filter((a:any)=>a.active).map((a:any)=>a.weekday));if(availability[0]){setStart(availability[0].start_time);setEnd(availability[0].end_time);setDuration(availability[0].slot_minutes)}};useEffect(()=>{void load()},[]);
 const save=async()=>{setMessage('');const r=await fetch('/api/clinic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'availability',days:selected,startTime:start,endTime:end,slotMinutes:duration})});const j=await r.json();if(!r.ok)return setMessage(j.error);setMessage('تم حفظ أوقات الدوام');await load()};
 const remove=async(id:number)=>{if(!window.confirm('هل تريد حذف هذا الحجز؟'))return;const r=await fetch(`/api/clinic?id=${id}`,{method:'DELETE'});const j=await r.json();if(!r.ok)return setMessage(j.error||'تعذر حذف الحجز');setMessage('تم حذف الحجز');await load()};
 return <main dir="rtl" className="doctor-page"><aside><div className="logo"><b>♡</b>{clinicConfig.clinicName}</div><button className={tab==='appointments'?'active':''} onClick={()=>setTab('appointments')}>▣ الحجوزات والمواعيد</button><button className={tab==='availability'?'active':''} onClick={()=>setTab('availability')}>◷ أوقات الفراغ</button><button className="logout" onClick={logout}>تسجيل الخروج</button></aside><section className="doctor-content"><header><div><h1>{tab==='appointments'?'الحجوزات والمواعيد':'تحديد أوقات الفراغ'}</h1><p>مرحباً {data.doctor?.name}</p></div><span className="doctor-pill">الطبيب</span></header>{message&&tab==='appointments'&&<p className={message.startsWith('تم')?'ok':'error'}>{message}</p>}{tab==='appointments'?<Appointments rows={data.appointments??[]} onDelete={remove}/>:<section className="availability panel"><h2>أيام وساعات الدوام</h2><p>الأوقات التي تحددها هنا هي فقط التي ستظهر للمريض.</p><div className="day-grid">{days.map(d=><button type="button" key={d.id} className={selected.includes(d.id)?'selected':''} onClick={()=>setSelected(v=>v.includes(d.id)?v.filter(x=>x!==d.id):[...v,d.id])}>{d.name}</button>)}</div><div className="time-settings"><label>بداية الدوام<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>نهاية الدوام<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>مدة الموعد<select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={15}>15 دقيقة</option><option value={30}>30 دقيقة</option><option value={45}>45 دقيقة</option><option value={60}>ساعة</option></select></label></div>{message&&<p className={message.startsWith('تم')?'ok':'error'}>{message}</p>}<button className="primary" onClick={save}>حفظ أوقات الدوام</button></section>}</section></main>}

function Appointments({rows,onDelete}:{rows:any[];onDelete:(id:number)=>void}){const grouped=(rows??[]).reduce((g:any,a:any)=>{(g[a.appointment_date]??=[]).push(a);return g},{});return <div className="appointment-list">{Object.keys(grouped).length===0?<div className="empty panel">لا توجد حجوزات قادمة.</div>:Object.entries(grouped).map(([date,list]:any)=><section className="date-group panel" key={date}><h2>{fmt(date)}</h2>{list.map((a:any)=><div className="appointment" key={a.id}><strong>{a.appointment_time}</strong><div><h3>{a.patient_name}</h3><a href={`tel:${a.patient_phone}`}>{a.patient_phone}</a></div><button className="delete-booking" onClick={()=>onDelete(a.id)}>حذف الحجز</button></div>)}</section>)}</div>}
